#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Band structure comparison tool for Quantum ESPRESSO and Wannier90.

This module provides functionality to compare band structures calculated using
Quantum ESPRESSO (PWSCF) with those obtained from Wannier90 interpolation.
The comparison is performed by plotting both band structures on the same graph
with proper k-path normalization and Fermi energy alignment.

Author: Generated by cif2qewan
"""

# Import the main function from the original module
import sys
import os

# Add the parent directory to the path to import the original module
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def main():
    """
    Main entry point for band_comp command-line interface.
    """
    # Import and run the main function from the original band_comp.py
    import band_comp as band_comp_module
    band_comp_module.main()

if __name__ == "__main__":
    main()