#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
CIF to Quantum ESPRESSO Wannier90 input generator.

This module provides functionality to generate Quantum ESPRESSO and Wannier90
input files from CIF (Crystallographic Information File) structures. It supports
both standard DFT calculations and advanced features like spin-orbit coupling
and magnetic calculations.

Usage:
    cif2qewan.py <cif_file> <toml_file> [--so] [--mag]

Options:
    --so     input including spin-orbit couplings
    --mag    ferromagnetic calculations

Author: Generated by cif2qewan
"""

import os

# Import the main function from the original module
import sys

# Add the parent directory to the path to import the original module
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def main():
    """
    Main entry point for cif2qewan command-line interface.
    """
    # Import and run the main function from the original cif2qewan.py
    import cif2qewan as cif2qewan_module

    # Call the main function directly from the module
    if hasattr(cif2qewan_module, "main"):
        cif2qewan_module.main()
    else:
        # Fallback: run the original script directly
        import os
        import subprocess
        import sys

        script_path = os.path.join(
            os.path.dirname(os.path.dirname(__file__)), "cif2qewan.py"
        )
        subprocess.run([sys.executable, script_path] + sys.argv[1:])


if __name__ == "__main__":
    main()
