#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
CIF to Quantum ESPRESSO Wannier90 input generator.

This module provides functionality to generate Quantum ESPRESSO and Wannier90
input files from CIF (Crystallographic Information File) structures. It supports
both standard DFT calculations and advanced features like spin-orbit coupling
and magnetic calculations.

Usage:
    cif2qewan.py <cif_file> <toml_file> [--so] [--mag]

Options:
    --so     input including spin-orbit couplings
    --mag    ferromagnetic calculations

Author: Generated by cif2qewan
"""

import sys
from importlib.machinery import SourceFileLoader
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path


def _load_cli_module():
    """Load the actual CLI implementation from the installed module file."""
    script_path = Path(__file__).resolve().parent.parent / "cif2qewan.py"
    if not script_path.exists():
        raise FileNotFoundError(f"CLI module not found at expected path: {script_path}")

    spec = spec_from_file_location("cif2qewan_cli", script_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load specification from {script_path}")

    module = module_from_spec(spec)
    loader = spec.loader
    assert isinstance(loader, SourceFileLoader)
    loader.exec_module(module)
    return module


def main():
    """Main entry point for cif2qewan console script."""
    module = _load_cli_module()
    if hasattr(module, "main"):
        module.main()
    else:
        raise AttributeError("cif2qewan.py does not define a main() function")


if __name__ == "__main__":
    main()
