#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Wannier90 convergence checker.

This module provides functionality to check the accuracy of Wannier90
interpolation by comparing the interpolated band structure with the
original DFT band structure from Quantum ESPRESSO calculations.

Author: Generated by cif2qewan
"""

import os

# Import the main function from the original module
import sys

# Add the parent directory to the path to import the original module
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def main():
    """
    Main entry point for wannier_conv command-line interface.
    """
    # Import and run the main function from the original wannier_conv.py
    import wannier_conv as wannier_conv_module

    wannier_conv_module.main()


if __name__ == "__main__":
    main()
