"""Tests for the structure readers.

The cif2cell adapter is exercised with a fake ``cif2cell`` script, so that
neither cif2cell nor a network connection is needed.
``test_both_readers_agree_on_fe`` checks that the pymatgen reader and the
cif2cell output describe the same crystal within tolerance.
"""

import os
import stat
import sys
import textwrap

import numpy as np
import pytest

from cif2qewan.exceptions import ExternalCommandError, StructureError
from cif2qewan.structure.compare import compare_structures, structures_equivalent
from cif2qewan.structure.model import AtomicSite, MagneticMoment, NormalizedStructure
from cif2qewan.structure.readers import (
    Cif2cellReader,
    PymatgenReader,
    StructureReader,
    parse_cif2cell_output,
)
from conftest import EXAMPLES

FE = EXAMPLES / "PSLibrary" / "Fe"
ALAT = 2.86304


# --------------------------------------------------------------------------
# cif2cell output parser
# --------------------------------------------------------------------------


def test_parse_fe_cif2cell_output():
    out = Cif2cellReader.read_output(FE / "cif_scf.in")
    s = out.structure
    assert s.num_sites == 1
    assert s.sites[0].element == "Fe" and s.sites[0].label == "Fe"
    assert s.sites[0].frac_coords == (0.0, 0.0, 0.0)
    assert s.volume == pytest.approx(ALAT**3 / 2.0)
    assert out.alat == pytest.approx(ALAT)
    assert np.array(out.cell_alat) == pytest.approx(
        np.array([[-0.5, 0.5, 0.5], [0.5, -0.5, 0.5], [0.5, 0.5, -0.5]])
    )
    assert list(out.masses) == ["Fe"]
    assert out.masses["Fe"] == pytest.approx(55.845)
    assert out.kmesh == (21, 21, 21)
    assert "Generated by cif2cell" in out.text


def test_parse_rejects_unusable_output():
    with pytest.raises(StructureError, match="nat/ntyp"):
        parse_cif2cell_output("&SYSTEM\n  ibrav = 0\n/\n")
    text = (FE / "cif_scf.in").read_text()
    with pytest.raises(StructureError, match="ibrav"):
        parse_cif2cell_output(text.replace("ibrav = 0", "ibrav = 3"))
    with pytest.raises(StructureError, match="cannot parse cif2cell output"):
        parse_cif2cell_output(text.replace("ibrav = 0", "ibrav = invalid"))
    with pytest.raises(StructureError, match="ATOMIC_SPECIES"):
        parse_cif2cell_output(
            text.replace("Fe   0.000000000000000", "Co   0.000000000000000")
        )
    with pytest.raises(StructureError, match="nat = 1"):
        parse_cif2cell_output(
            text.replace(
                "Fe   0.000000000000000   0.000000000000000   0.000000000000000 \n",
                "Fe   0.0 0.0 0.0\nFe   0.5 0.5 0.5\n",
            )
        )


def test_parse_accepts_angstrom_and_bohr_cells():
    text = textwrap.dedent("""
        &SYSTEM
          ibrav = 0
          nat = 1
          ntyp = 1
        /
        CELL_PARAMETERS {angstrom}
          4.0 0.0 0.0
          0.0 4.0 0.0
          0.0 0.0 4.0
        ATOMIC_SPECIES
          Na 22.99 Na_PSEUDO
        ATOMIC_POSITIONS {crystal}
        Na 0.0 0.0 0.0
        """)
    out = parse_cif2cell_output(text)
    assert out.structure.volume == pytest.approx(64.0)
    assert out.alat == pytest.approx(4.0)
    assert out.kmesh is None

    bohr = text.replace("{angstrom}", "{bohr}")
    assert parse_cif2cell_output(bohr).structure.volume == pytest.approx(
        64.0 * 0.529177210903**3
    )


def test_read_output_requires_an_existing_file(tmp_path):
    with pytest.raises(StructureError, match="not found"):
        Cif2cellReader.read_output(tmp_path / "missing.in")


# --------------------------------------------------------------------------
# cif2cell subprocess adapter
# --------------------------------------------------------------------------


def fake_cif2cell(tmp_path, behaviour):
    """A stand-in for cif2cell that records its arguments.

    behaviour: "ok" writes the Fe output to the -o path, "fail" exits 2 with
    a message, "silent" exits 0 without writing anything.
    """
    script = tmp_path / "fake_cif2cell.py"
    script.write_text(textwrap.dedent(f"""
            import pathlib, sys
            args = sys.argv[1:]
            pathlib.Path({str(tmp_path / "args.txt")!r}).write_text("\\n".join(args))
            pathlib.Path({str(tmp_path / "cwd.txt")!r}).write_text(str(pathlib.Path.cwd()))
            behaviour = {behaviour!r}
            if behaviour == "fail":
                sys.stderr.write("cif2cell: cannot parse CIF\\n")
                sys.exit(2)
            if behaviour == "ok":
                out = args[args.index("-o") + 1]
                pathlib.Path(out).write_text(pathlib.Path({str(FE / "cif_scf.in")!r}).read_text())
            """))
    launcher = tmp_path / "cif2cell"
    launcher.write_text(f'#!/bin/sh\nexec {sys.executable} {script} "$@"\n')
    launcher.chmod(launcher.stat().st_mode | stat.S_IEXEC)
    return launcher


def test_reader_runs_cif2cell_in_a_temporary_directory(tmp_path, monkeypatch):
    workdir = tmp_path / "work"
    workdir.mkdir()
    monkeypatch.chdir(workdir)
    cif = tmp_path / "Fe (test) ü.cif"
    cif.write_text((FE / "mp-13_Fe.cif").read_text())

    reader = Cif2cellReader(fake_cif2cell(tmp_path, "ok"), k_resolution=0.15)
    out = reader.run(cif)

    assert out.kmesh == (21, 21, 21)
    args = (tmp_path / "args.txt").read_text().splitlines()
    assert args[:4] == ["-p", "pwscf", "--setup-all", "--k-resolution=0.150"]
    assert "--print-digits=10" in args
    assert args[-1] == str(cif.resolve())  # passed as one argument, unescaped
    run_cwd = (tmp_path / "cwd.txt").read_text()
    assert run_cwd != str(workdir) and not os.path.exists(run_cwd)  # temp dir, cleaned
    assert not (
        workdir / "cif_scf.in"
    ).exists()  # nothing left in the working directory
    assert os.getcwd() == str(workdir)

    structure = reader.read(cif)
    assert structure == out.structure


def test_reader_reports_cif2cell_failures(tmp_path):
    cif = tmp_path / "x.cif"
    cif.write_text("data_x\n")

    with pytest.raises(ExternalCommandError) as info:
        Cif2cellReader(fake_cif2cell(tmp_path, "fail")).run(cif)
    assert info.value.returncode == 2
    assert "cannot parse CIF" in str(info.value)

    with pytest.raises(ExternalCommandError, match="wrote no cif_scf.in"):
        Cif2cellReader(fake_cif2cell(tmp_path, "silent")).run(cif)

    with pytest.raises(ExternalCommandError, match="cannot run cif2cell"):
        Cif2cellReader(tmp_path / "does_not_exist").run(cif)

    with pytest.raises(StructureError, match="CIF file not found"):
        Cif2cellReader(fake_cif2cell(tmp_path, "ok")).run(tmp_path / "missing.cif")


def test_readers_satisfy_the_protocol():
    assert isinstance(Cif2cellReader("cif2cell"), StructureReader)
    assert isinstance(PymatgenReader(), StructureReader)


# --------------------------------------------------------------------------
# pymatgen reader
# --------------------------------------------------------------------------

pymatgen = pytest.importorskip("pymatgen")


def test_pymatgen_reader_primitive_and_conventional():
    primitive = PymatgenReader().read(FE / "mp-13_Fe.cif")
    assert primitive.num_sites == 1
    assert primitive.elements == ("Fe",)
    assert primitive.volume == pytest.approx(2.8630355**3 / 2.0)

    conventional = PymatgenReader(primitive=False).read(FE / "mp-13_Fe.cif")
    assert conventional.num_sites == 2
    assert conventional.volume == pytest.approx(2.8630355**3)
    assert not conventional.is_magnetic


def test_both_readers_agree_on_fe():
    """Step 3 completion criterion: physically equivalent structures."""
    from_cif2cell = Cif2cellReader.read_output(FE / "cif_scf.in").structure
    from_pymatgen = PymatgenReader().read(FE / "mp-13_Fe.cif")
    assert compare_structures(from_cif2cell, from_pymatgen) == []
    # but the conventional cell is not the same structure description
    conventional = PymatgenReader(primitive=False).read(FE / "mp-13_Fe.cif")
    assert not structures_equivalent(from_cif2cell, conventional)


def test_pymatgen_reader_errors(tmp_path):
    with pytest.raises(StructureError, match="not found"):
        PymatgenReader().read(tmp_path / "missing.cif")
    bad = tmp_path / "bad.cif"
    bad.write_text("this is not a cif\n")
    with pytest.raises(StructureError):
        PymatgenReader().read(bad)


def test_pymatgen_conversion_keeps_magmom_and_rejects_mixed_sites():
    from pymatgen.core import Lattice, Structure

    structure = Structure(
        Lattice.cubic(2.8),
        ["Fe", "Fe"],
        [[0, 0, 0], [0.5, 0.5, 0.5]],
        site_properties={"magmom": [[0, 0, 2.2], [0, 0, -2.2]]},
    )
    normalized = PymatgenReader.from_pymatgen(structure)
    assert normalized.is_magnetic
    assert normalized.sites[0].magmom.vector == pytest.approx((0.0, 0.0, 2.2))
    assert normalized.sites[1].magmom.vector == pytest.approx((0.0, 0.0, -2.2))

    collinear = Structure(
        Lattice.cubic(2.8), ["Fe"], [[0, 0, 0]], site_properties={"magmom": [2.2]}
    )
    assert PymatgenReader.from_pymatgen(collinear).sites[
        0
    ].magmom.vector == pytest.approx((0.0, 0.0, 2.2))

    mixed = Structure(Lattice.cubic(4.0), [{"Na": 0.5, "K": 0.5}], [[0, 0, 0]])
    with pytest.raises(StructureError, match="mixed occupancy"):
        PymatgenReader.from_pymatgen(mixed)

    partial = Structure(Lattice.cubic(4.0), [{"Na": 0.5}], [[0, 0, 0]])
    with pytest.raises(StructureError, match="partial occupancy"):
        PymatgenReader.from_pymatgen(partial)


# --------------------------------------------------------------------------
# structure comparison
# --------------------------------------------------------------------------

BCC = np.array([[-0.5, 0.5, 0.5], [0.5, -0.5, 0.5], [0.5, 0.5, -0.5]]) * ALAT
BCC_OTHER = np.array([[0.5, 0.5, 0.5], [0.5, -0.5, -0.5], [-0.5, 0.5, -0.5]]) * ALAT


def test_compare_accepts_other_primitive_vectors_and_translations():
    a = NormalizedStructure(BCC, (AtomicSite("Fe", (0, 0, 0)),))
    b = NormalizedStructure(BCC_OTHER, (AtomicSite("Fe", (1.0, -2.0, 3.0)),))
    assert compare_structures(a, b) == []

    nacl_a = NormalizedStructure(
        np.eye(3) * 4.0,
        (AtomicSite("Na", (0, 0, 0)), AtomicSite("Cl", (0.5, 0.5, 0.5))),
    )
    nacl_b = NormalizedStructure(
        np.eye(3) * 4.0,
        (AtomicSite("Cl", (-0.5, 0.5, 1.5)), AtomicSite("Na", (1.0, 0.0, 0.0))),
    )
    assert structures_equivalent(nacl_a, nacl_b)  # sites reordered and translated
    shifted_origin = NormalizedStructure(
        np.eye(3) * 4.0,
        (AtomicSite("Na", (0.25, 0.25, 0.25)), AtomicSite("Cl", (0.75, 0.75, 0.75))),
    )
    assert not structures_equivalent(
        nacl_a, shifted_origin
    )  # same crystal, other frame


def test_compare_reports_differences():
    a = NormalizedStructure(BCC, (AtomicSite("Fe", (0, 0, 0)),))
    supercell = NormalizedStructure(
        np.eye(3) * ALAT,
        (AtomicSite("Fe", (0, 0, 0)), AtomicSite("Fe", (0.5, 0.5, 0.5))),
    )
    (difference,) = compare_structures(a, supercell)
    assert difference.startswith("volumes differ: 11.734167 vs 23.4683")

    rotated = NormalizedStructure(BCC[[1, 2, 0]] * np.array([1, 1, 1.0001]), a.sites)
    assert compare_structures(a, rotated)[0].startswith("volumes differ")

    other_element = NormalizedStructure(BCC, (AtomicSite("Co", (0, 0, 0)),))
    assert compare_structures(a, other_element) == [
        "no counterpart for Co at (0.0, 0.0, 0.0)"
    ]

    moved = NormalizedStructure(BCC, (AtomicSite("Fe", (0.1, 0, 0)),))
    assert len(compare_structures(a, moved)) == 1

    up = NormalizedStructure(
        BCC, (AtomicSite("Fe", (0, 0, 0), MagneticMoment((0, 0, 2.2))),)
    )
    down = NormalizedStructure(
        BCC, (AtomicSite("Fe", (0, 0, 0), MagneticMoment((0, 0, -2.2))),)
    )
    assert not structures_equivalent(up, down)
    assert not structures_equivalent(up, a)
    assert structures_equivalent(
        a, a.with_sites([AtomicSite("Fe", (0, 0, 0), MagneticMoment.zero())])
    )
