"""Render a :class:`Wannier90Input` to ``.win`` text.

Layout (fixed, independent of how the model was built)::

    ! generated by cif2qewan.py
    num_bands = ...
    num_wann = ...
    exclude_bands = a-b          (if any)

    spinors = .true.             (if spinors)

    <pass-through parameters, one per line, in insertion order>

    begin projections ... end projections
    begin unit_cell_cart ... end unit_cell_cart
    begin atoms_frac ... end atoms_frac
    mp_grid: n1 n2 n3
    begin kpoints ... end kpoints
    begin kpoint_path ... end kpoint_path   (if any)

Compared with 0.2.x the parameters are no longer split into blocks around
the projections and ``num_wann`` is written with a single space; the
numeric formats are unchanged.
"""

from __future__ import annotations

from cif2qewan.exceptions import InputModelError
from cif2qewan.wannier90.model import ParameterValue, Wannier90Input

#: First line of every generated file. Kept from 0.2.x for compatibility.
HEADER = "! generated by cif2qewan.py"


def format_parameter(value: ParameterValue) -> str:
    """Wannier90 literal: ``.true.``/``.false.``, numbers, strings unquoted."""
    if isinstance(value, bool):
        return ".true." if value else ".false."
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return value
    raise InputModelError(f"cannot format Wannier90 parameter {value!r}")


def _block(name: str, lines) -> str:
    return f"begin {name}\n" + "".join(line + "\n" for line in lines) + f"end {name}\n"


def render_win(win: Wannier90Input, header: str = HEADER) -> str:
    """Complete text of the ``.win`` file."""
    parts = [header + "\n"]
    parts.append(f"num_bands = {win.num_bands}\n")
    parts.append(f"num_wann = {win.num_wann}\n")
    if win.exclude_bands is not None:
        first, last = win.exclude_bands
        parts.append(f"exclude_bands = {first}-{last}\n")
    parts.append("\n")

    if win.spinors:
        parts.append("spinors = .true.\n\n")

    if win.parameters:
        for key, value in win.parameters.items():
            parts.append(f"{key} = {format_parameter(value)}\n")
        parts.append("\n")

    parts.append(
        _block(
            "projections",
            (f"{p.site}:{','.join(p.orbitals)}" for p in win.projections),
        )
        + "\n"
    )

    cell_rows = (
        f"{row[0]:12.7f} {row[1]:12.7f} {row[2]:12.7f}" for row in win.unit_cell_cart
    )
    parts.append(_block("unit_cell_cart", ["ang", *cell_rows]) + "\n")

    atom_rows = (
        f"{atom.label:<3}" + "".join(f"{x:19.15f} " for x in atom.coords)
        for atom in win.atoms_frac
    )
    parts.append(_block("atoms_frac", atom_rows) + "\n")

    parts.append(f"mp_grid: {win.mp_grid[0]} {win.mp_grid[1]} {win.mp_grid[2]}\n\n")

    k_rows = (f"{k[0]:15.10f} {k[1]:15.10f} {k[2]:15.10f}" for k in win.kpoints)
    parts.append(_block("kpoints", k_rows))

    if win.kpoint_path:
        path_rows = (
            f"{s.start_label} {s.start[0]:14.10f} {s.start[1]:14.10f} {s.start[2]:14.10f}  "
            f"{s.end_label} {s.end[0]:14.10f} {s.end[1]:14.10f} {s.end[2]:14.10f}"
            for s in win.kpoint_path
        )
        parts.append("\n" + _block("kpoint_path", path_rows))

    return "".join(parts)
