"""Render Quantum ESPRESSO input models to text.

The functions here only format typed models; they choose no physical
parameter and write no file. The formatting reproduces the 0.2.x output
of cif2qewan, with one normalization: every ``K_POINTS`` option is written
in braces (``K_POINTS {automatic}``), whereas 0.2.x copied ``K_POINTS
automatic`` verbatim from cif2cell for the SCF input. Both spellings are
accepted by ``pw.x``.
"""

from __future__ import annotations

from typing import Union

from cif2qewan.exceptions import InputModelError
from cif2qewan.qe.model import (
    KPoints,
    KPointsAutomatic,
    KPointsList,
    KPointsPath,
    Namelist,
    NamelistInput,
    NamelistValue,
    PwInput,
    RawValue,
)

#: First line of every generated file. Kept from 0.2.x for compatibility.
HEADER = "! generated by cif2qewan.py"


def format_value(value: NamelistValue) -> str:
    """Fortran namelist literal for a typed value.

    ``bool`` -> ``.true.``/``.false.``, ``str`` -> single-quoted, ``int`` ->
    decimal, ``float`` -> shortest round-trip repr (``64.0``, ``0.1``),
    ``RawValue`` -> its literal unchanged.
    """
    if isinstance(value, RawValue):
        return value.literal
    if isinstance(value, bool):
        return ".true." if value else ".false."
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        if "'" in value:
            raise InputModelError(f"namelist string {value!r} must not contain a quote")
        return f"'{value}'"
    raise InputModelError(f"cannot format namelist value {value!r}")


def render_namelist(namelist: Namelist, indent: str = "  ") -> str:
    """``&name`` ... ``/`` with one ``key = value`` line per entry, in order."""
    lines = [f"&{namelist.name}"]
    for key, value in namelist.entries.items():
        lines.append(f"{indent}{key} = {format_value(value)}")
    lines.append("/")
    return "\n".join(lines) + "\n"


def render_kpoints(kpoints: KPoints) -> str:
    """The ``K_POINTS`` card, ending with a newline."""
    if isinstance(kpoints, KPointsAutomatic):
        mesh = " ".join(str(n) for n in kpoints.mesh)
        shift = " ".join(str(s) for s in kpoints.shift)
        return f"K_POINTS {{automatic}}\n{mesh}  {shift}\n"
    if isinstance(kpoints, KPointsList):
        lines = [f"K_POINTS {{{kpoints.option}}}", str(kpoints.num_points)]
        for kx, ky, kz, weight in kpoints.points:
            lines.append(f"{kx:15.10f} {ky:15.10f} {kz:15.10f} {weight:15.10f}")
        return "\n".join(lines) + "\n"
    if isinstance(kpoints, KPointsPath):
        lines = [f"K_POINTS {{{kpoints.option}}}", str(kpoints.num_points)]
        for point in kpoints.points:
            kx, ky, kz = point.coords
            lines.append(
                f"{kx:15.10f} {ky:15.10f} {kz:15.10f}  {point.ndiv:>4d}    !  {point.label}"
            )
        return "\n".join(lines) + "\n"
    raise InputModelError(f"cannot render K_POINTS {kpoints!r}")


def _vector_row(values) -> str:
    return "".join(f"{x:19.15f} " for x in values)


def render_pw_input(pw: PwInput, header: str = HEADER) -> str:
    """Complete text of a ``pw.x`` input."""
    parts = [header + "\n"]
    parts.append(render_namelist(pw.control))
    parts.append(render_namelist(pw.system))
    parts.append(render_namelist(pw.electrons))

    if pw.cell is not None:
        rows = "".join(_vector_row(row) + "\n" for row in pw.cell.vectors)
        parts.append(f"CELL_PARAMETERS {{{pw.cell.option}}}\n{rows}\n")

    species = "".join(
        f"  {s.label}   {s.mass:.5f}  {s.pseudo_file}\n" for s in pw.species
    )
    parts.append(f"ATOMIC_SPECIES\n{species}\n")

    positions = "".join(f"{p.label:<3}{_vector_row(p.coords)}\n" for p in pw.positions)
    parts.append(f"ATOMIC_POSITIONS {{{pw.positions_option}}}\n{positions}\n")

    parts.append(render_kpoints(pw.kpoints) + "\n")
    return "".join(parts)


def render_namelist_input(
    inp: NamelistInput, indent: str = " ", header: str = HEADER
) -> str:
    """Text of a namelist-only input (``bands.x``, ``pw2wannier90.x``, ...)."""
    return header + "\n" + "".join(render_namelist(n, indent) for n in inp.namelists)


def render(model: Union[PwInput, NamelistInput], header: str = HEADER) -> str:
    """Render either kind of QE input model."""
    if isinstance(model, PwInput):
        return render_pw_input(model, header)
    if isinstance(model, NamelistInput):
        return render_namelist_input(model, header=header)
    raise InputModelError(f"cannot render {model!r}")
